// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfacazldwwaqoevhidsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmYWNhemxkd3dhcW9ldmhpZHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNjU4NTQsImV4cCI6MjA4ODc0MTg1NH0.SOiA2tEgF0ygITYtrvj89O-D44zwUVl42sIEq9NSQpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
