// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bmvzdqqgafkdyrsounfa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJtdnpkcXFnYWZrZHlyc291bmZhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc1MzkwNzMsImV4cCI6MjA4MzExNTA3M30.pvZp64M4JHjI5oJ--MITFHZCMYH5NNIdERmsT8YZ2Sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});